apiVersion: v1alpha
kind: cypress
defaults:
  mode: sauce
sauce:
  region: us-west-1
  concurrency: 2
  metadata:
    name: saucectl cypress example
    tags:
      - e2e
      - release team
      - other tag
    build: Github Run $GITHUB_RUN_ID
docker:
  fileTransfer: copy
cypress:
  version: 7.3.0
  configFile: "cypress.json"
rootDir: ./
suites:
  - name: "Tutorial test - Windows Chrome"
    browser: "chrome"
    platformName: "Windows 10"
    screenResolution: "1920x1080"
    config:
      testFiles: ['**/login.spec.js'] # Cypress native glob support.
  - name: "Tutorial test - Windows Firefox 89"
    platformName: "Windows 10"
    browser: "firefox"
    browserVersion: "89.0"
    config:
      testFiles: ['**/login.spec.js']

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/
